#!/usr/bin/env bash

RED=$'\e[31m'
GREEN=$'\e[32m'
YELLOW=$'\e[33m'
RESET=$'\e[0m'

# Prompt for a boolean (yes/no) response
prompt_boolean() {
  local prompt_text="$1"
  local __resultvar="$2"
  local answer

  while true; do
    read -r -p "$prompt_text [y/N]: " answer
    echo
    case "$answer" in
    [yY])
      printf -v "$__resultvar" true
      break
      ;;
    [nN] | "")
      printf -v "$__resultvar" false
      break
      ;;
    *) printf "%b\n\n" "${RED}Invalid selection.${RESET}" ;;
    esac
  done
}

if pacman -Qtdq &>/dev/null; then
  echo -e "\n${GREEN}Orphaned packages:${RESET}"

  # List orphaned packages
  pacman -Qtdq
  echo

  # Remove orphaned packages after confirmation
  prompt_boolean "${YELLOW}Remove orphaned packages?${RESET}" confirmation
  if $confirmation; then
    echo -e "${GREEN}Removing orphaned packages...${RESET}"
    pacman -Qtdq | sudo pacman -Rns -
  else
    echo -e "${GREEN}Skipping removal of orphaned packages...${RESET}"
  fi
else
  echo -e "\n${GREEN}No orphaned packages found.${RESET}"
fi

# Go back to maintenance menu
exec $(dirname $(dirname $(realpath $0)))/run.sh -q
