#!/usr/bin/env bash

GREEN=$'\e[32m'
RESET=$'\e[0m'

OUTPUT_FILE="$HOME/Downloads/package_list.txt"

echo -e "\nExporting list of explicitly installed packages..."

# Export list of explicitly installed packages
pacman -Qqe >"$OUTPUT_FILE" &&
    echo -e "\n${GREEN}Package list saved to:${RESET} ${OUTPUT_FILE}"

# Back to main menu
exec "$(dirname "$(dirname "$(realpath "$0")")")/run.sh" -q
