#!/usr/bin/env bash

echo -e "\n"

# Backup the mirror list
sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup &&
  echo -e "Old mirror list saved to: /etc/pacman.d/mirrorlist.backup \n"

# Generate a new updated mirror list with reflector
sudo reflector -c Australia -a 6 --sort rate --verbose --save /etc/pacman.d/mirrorlist

# Return to menu
exec $(dirname $(dirname $(realpath $0)))/run.sh -q
